services:

  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
  
  celery:
    build: .
    container_name: celery_worker
    command: celery -A ecommerce_web_scraping worker --pool=solo -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis